import type { Ritual } from '@/types';

export const RITUALS: Ritual[] = [
  // Shadow Scholar
  {
    id: 'ss-perception-01',
    archetypeId: 'shadow-scholar',
    name: 'The Rite of Forbidden Perception',
    domain: 'focus',
    description: 'A ritual of sharpened sight — turning your pattern-recognition inward and then outward, with deliberate precision.',
    lore: 'The ancient Keepers of Veiled Truth practiced this rite at dawn, believing that the hours before full light were when the world\'s hidden structure was most visible.',
    duration: 15,
    steps: [
      'Find a space where you will not be interrupted. Dim or extinguish light sources.',
      'Sit in stillness for three minutes. Notice the silence between your thoughts.',
      'In a journal, write five things you have observed recently that others missed or dismissed.',
      'Choose one of these observations. Write everything it implies — follow every thread.',
      'Now turn the lens inward: write one thing you know about yourself that you have never said aloud.',
      'Close the journal. Sit with what you wrote for two minutes before moving.',
    ],
    symbolicFocus: 'A single unlit candle placed before you — the potential of what is not yet illuminated.',
    xpReward: 75,
    isPremium: false,
  },
  {
    id: 'ss-archive-02',
    archetypeId: 'shadow-scholar',
    name: 'The Shadow Archive',
    domain: 'reflection',
    description: 'A deep journaling rite that excavates the hidden architecture of your recent experiences.',
    lore: 'Shadow Scholars maintain archives of their inner state — not diaries, but analytical records of patterns they observe in their own behavior and the world around them.',
    duration: 20,
    steps: [
      'Open your journal to a fresh page. Write the date and "ARCHIVE ENTRY" at the top.',
      'Recall the three most emotionally charged moments from the past seven days.',
      'For each: write what happened on the surface. Then write what was actually happening beneath it.',
      'Identify the single pattern that connects all three.',
      'Write one sentence: "The truth I am avoiding is..." and complete it without censoring.',
      'Seal the entry by writing the sentence: "I see. I do not need to be seen."',
    ],
    symbolicFocus: 'Black ink on white paper — the act of making the invisible visible.',
    xpReward: 100,
    isPremium: false,
  },
  {
    id: 'ss-void-sight-03',
    archetypeId: 'shadow-scholar',
    name: 'The Void Sight Protocol',
    domain: 'discipline',
    description: 'An advanced perception ritual for the Shadow Scholar who seeks to read the deeper structure of their current path.',
    lore: 'The most advanced scholars in the forbidden orders practiced this rite monthly — a full reckoning of the gap between what they believed and what they actually knew.',
    duration: 30,
    steps: [
      'Clear your space completely. Remove objects that represent obligations or urgency.',
      'Write at the top of a page: "What I believe vs. What I can prove."',
      'List five beliefs you currently hold about your life, your relationships, or yourself.',
      'For each belief: find the single piece of evidence that could disprove it.',
      'Sit with the uncertainty this creates. Do not rush to resolve it.',
      'Write the single action that would most align your life with what you actually know to be true.',
      'Commit to this action in writing. Sign it with the date.',
    ],
    symbolicFocus: 'Two facing mirrors — the self reflected infinitely, each reflection slightly different.',
    xpReward: 150,
    isPremium: true,
  },

  // Lunar Seer
  {
    id: 'ls-tide-01',
    archetypeId: 'lunar-seer',
    name: 'The Tide Reading',
    domain: 'emotional',
    description: 'A ritual for the Lunar Seer to locate themselves within the emotional cycles they are currently navigating.',
    lore: 'Tide Prophets of the old orders mapped their inner state as they would map the sea — not fighting the current but understanding it completely.',
    duration: 15,
    steps: [
      'Find water if possible — a glass, a sink, the sound of rain. If not, visualize it.',
      'Close your eyes. Breathe slowly for two minutes, following the rhythm of your breath as tide.',
      'Ask yourself: "What am I currently moving toward, and what am I moving away from?"',
      'Write both answers. Do not judge them. They are simply the current direction.',
      'Ask: "Is this direction chosen, or is it the momentum of something that should end?"',
      'Sit with the distinction. Write three words that describe where you actually want to go.',
    ],
    symbolicFocus: 'Water in any form — the element that holds memory and moves in cycles.',
    xpReward: 75,
    isPremium: false,
  },
  {
    id: 'ls-dream-02',
    archetypeId: 'lunar-seer',
    name: 'The Dream Harvest',
    domain: 'reflection',
    description: 'A morning ritual for capturing and interpreting the intelligence carried in dreams.',
    lore: 'The ancient Lunar Seers believed that sleep was a secondary state of consciousness — not absence of mind but its deeper operation. The Dream Harvest treats the contents of sleep as primary data.',
    duration: 10,
    steps: [
      'Immediately upon waking, before speaking or looking at a screen, write whatever fragments remain from your dreams.',
      'Do not analyze yet. Record images, feelings, colors, presences, movements.',
      'Now identify the single strongest emotion from the dream.',
      'Write: "This emotion is also present in my waking life as..." and complete without overthinking.',
      'Write one practical thing the dream\'s intelligence might be pointing toward.',
      'Close your journal. Trust that more of the message will surface during the day.',
    ],
    symbolicFocus: 'The first light of morning — the threshold between the dreaming and waking states.',
    xpReward: 60,
    isPremium: false,
  },
  {
    id: 'ls-moon-03',
    archetypeId: 'lunar-seer',
    name: 'The Silver Immersion',
    domain: 'calmness',
    description: 'A deep emotional restoration rite for the Seer who has been absorbing too much.',
    lore: 'When the Tide Prophets had spent too long in the presence of others\' storms, they returned to this rite — a full recalibration of emotional sovereignty.',
    duration: 25,
    steps: [
      'Prepare a space with no demands — no notifications, no obligations visible.',
      'Breathe deeply for five minutes, exhaling slowly. With each exhale, name something you are releasing.',
      'Identify one emotion you are currently carrying that is not originally yours.',
      'Visualize returning it — gently, without judgment — to its source.',
      'Now ask: "What is my actual emotional state beneath everything I am carrying?"',
      'Write that state in a single sentence. Sit with it. It is the truth beneath the tide.',
      'End by writing three things that are entirely, genuinely yours.',
    ],
    symbolicFocus: 'Silver light — the moon\'s reflected glow, calm and discerning.',
    xpReward: 120,
    isPremium: false,
  },

  // Ashborn Monarch
  {
    id: 'am-sovereign-01',
    archetypeId: 'ashborn-monarch',
    name: 'The Sovereign Morning',
    domain: 'discipline',
    description: 'A daily ritual establishing the authority of your intentions before the world has a chance to set its agenda for you.',
    lore: 'The Phoenix Sovereigns of the ancient orders understood that the morning was a battle for the soul\'s direction — won or lost before most people had opened their eyes.',
    duration: 20,
    steps: [
      'Wake before you need to. Claim this time as non-negotiable territory.',
      'Do not check anything external for the first ten minutes. This time belongs to you.',
      'Write the single most important thing you must do today for your sovereign path.',
      'Write the single thing you are refusing, this day, regardless of pressure.',
      'Breathe slowly for three minutes. With each inhale, receive the day\'s potential. With each exhale, release yesterday\'s weight.',
      'Speak aloud: "I have survived harder than this. I know what I am building." Then begin.',
    ],
    symbolicFocus: 'The moment before full light — the hour when the Monarch claims their day.',
    xpReward: 80,
    isPremium: false,
  },
  {
    id: 'am-fire-02',
    archetypeId: 'ashborn-monarch',
    name: 'The Phoenix Protocol',
    domain: 'confidence',
    description: 'A ritual for moving through failure with the transmutative power of the phoenix.',
    lore: 'The ashborn tradition teaches that failure is not the opposite of success — it is the material from which success is forged. This rite treats setback as sacred raw material.',
    duration: 15,
    steps: [
      'Identify the most recent failure or setback. Write it without softening.',
      'Write what this failure has confirmed about what does not work.',
      'Write what this failure has revealed about what you are actually capable of enduring.',
      'Write three specific things you now know that you could not have known without this failure.',
      'Ask: "What would I build if I were not afraid of this happening again?"',
      'Write one step toward that building. Make it specific. Make it today.',
    ],
    symbolicFocus: 'Ash — the remains of what burned, containing the minerals that feed new growth.',
    xpReward: 100,
    isPremium: false,
  },

  // Silent Alchemist
  {
    id: 'sa-process-01',
    archetypeId: 'silent-alchemist',
    name: 'The Transmutation Vigil',
    domain: 'discipline',
    description: 'A ritual honoring the invisible work — the process that no one sees but that produces all visible results.',
    lore: 'The great Alchemists of the ancient orders spent more time in preparation and documentation than in active work. They understood that process was not the means to the result — it was the art.',
    duration: 25,
    steps: [
      'Choose one ongoing project, relationship, or personal development. One thing you are slowly becoming.',
      'Write where you were with it six months ago. Be specific.',
      'Write where you are now. Note every small change, however invisible it appears.',
      'Identify the single process — the practice, the habit, the daily act — that has created the most movement.',
      'Recommit to this process in writing. Not to the outcome. To the act itself.',
      'Close with this: "The work is the way. The way is the work."',
    ],
    symbolicFocus: 'A seed that has not yet broken surface — the power of what is becoming.',
    xpReward: 90,
    isPremium: false,
  },
  {
    id: 'sa-patience-02',
    archetypeId: 'silent-alchemist',
    name: 'The Long Stone',
    domain: 'calmness',
    description: 'A grounding ritual for returning to the deep patience that is your primary power.',
    lore: 'Stone endures not through resistance but through its nature. The Long Stone ritual returns the Alchemist to their fundamental quality — the calm that outlasts all storms.',
    duration: 20,
    steps: [
      'Sit without any task. No journal, no phone, no agenda. Simply be present.',
      'Notice every urge to move, to do, to accomplish. Do not act on them.',
      'After ten minutes, ask: "What in my life am I rushing that should be slow?"',
      'Write the answer. Sit with it.',
      'Ask: "What result am I trying to force that would come naturally if I gave it its proper time?"',
      'Write the answer. This is what needs your patience, not your urgency.',
      'End by sitting for three more minutes in complete stillness. Let the stone be stone.',
    ],
    symbolicFocus: 'A smooth stone — shaped by time rather than effort.',
    xpReward: 85,
    isPremium: false,
  },

  // Storm Vessel
  {
    id: 'sv-lightning-01',
    archetypeId: 'storm-vessel',
    name: 'The Directed Lightning',
    domain: 'ambition',
    description: 'A ritual for channeling the Storm Vessel\'s intensity into a single focused direction.',
    lore: 'The Tempest Conduits of the old orders did not practice stillness as their primary discipline. They practiced direction. A storm without direction is destruction. A storm with direction is weather that changes landscapes.',
    duration: 20,
    steps: [
      'Begin with five minutes of intense physical movement — enough to fully activate your body.',
      'At the point of maximum energy, stop completely. Sit.',
      'Write: "If I directed my full intensity at ONE thing for the next 30 days, it would be..."',
      'Write every obstacle to this direction. Do not soften them.',
      'Write how you will use your intensity to meet each obstacle.',
      'Speak aloud the commitment. Hear your own voice make the declaration.',
      'Return to physical movement for two minutes. Then stop. The storm has a direction now.',
    ],
    symbolicFocus: 'A lightning rod — not an absence of power but its direction.',
    xpReward: 95,
    isPremium: false,
  },
  {
    id: 'sv-eye-02',
    archetypeId: 'storm-vessel',
    name: 'The Eye of the Storm',
    domain: 'calmness',
    description: 'A ritual for finding the stillness at the center of your intensity.',
    lore: 'At the center of every storm is a region of absolute calm. This is not absence of the storm. The storm creates the eye. The Storm Vessel who can access their center does not become less powerful. They become directed.',
    duration: 15,
    steps: [
      'Find a quiet place. This may require effort. Do it anyway.',
      'Breathe in for 4 counts. Hold for 4. Out for 6. Repeat ten times.',
      'Notice the place beneath your intensity. The awareness watching the storm.',
      'Ask from that place: "What is the storm trying to accomplish?"',
      'Write the answer. This is your direction, not your chaos.',
      'Sit in the eye for five minutes. Feel the storm around it without being it.',
      'Carry the eye with you when you leave.',
    ],
    symbolicFocus: 'The space between heartbeats — the pause that makes the rhythm possible.',
    xpReward: 85,
    isPremium: false,
  },

  // Void Oracle
  {
    id: 'vo-presence-01',
    archetypeId: 'void-oracle',
    name: 'The Infinite Witness',
    domain: 'reflection',
    description: 'A practice of radical presence — the Oracle sitting fully with what is, without needing it to be different.',
    lore: 'The Void Oracle\'s primary discipline is not visualization or journaling — it is pure, undivided presence. This rite creates the conditions for the Oracle\'s deepest capacity: the witness that clarifies everything it touches.',
    duration: 20,
    steps: [
      'Sit in a comfortable position. No journal. No agenda.',
      'Observe what is present without naming it or categorizing it.',
      'When thoughts arise, do not follow them. Return to the observation.',
      'After ten minutes, allow one question to form: "What is actually happening in my life right now?"',
      'Receive whatever comes. Do not force. Do not analyze. Simply receive.',
      'When the answer has fully formed, sit with it for another five minutes before writing it.',
      'The writing is the record, not the practice. The practice was the witnessing.',
    ],
    symbolicFocus: 'An empty bowl — capable of holding anything precisely because it holds nothing.',
    xpReward: 90,
    isPremium: false,
  },
  {
    id: 'vo-null-02',
    archetypeId: 'void-oracle',
    name: 'The Nullification',
    domain: 'calmness',
    description: 'A rite of releasing attachment to outcomes, identities, and narratives that constrain the Oracle\'s sight.',
    lore: 'The Void Oracle\'s power grows not through addition but through subtraction. Each thing released creates greater clarity. This rite is a disciplined practice of letting go.',
    duration: 25,
    steps: [
      'List five things you are currently attached to — outcomes, opinions of you, self-concepts.',
      'For each: ask "Would I still be essentially myself without this?"',
      'For the ones where the answer is uncertain: sit with the uncertainty.',
      'Breathe slowly. Imagine holding each attachment in your hands. Feel its weight.',
      'One by one, open your hands. Not destroying them. Releasing the grip.',
      'Ask: "What am I, beneath everything I am trying to maintain?"',
      'Write one sentence from that place. This is your oracle.',
    ],
    symbolicFocus: 'Open hands — the gesture of receiving and releasing simultaneously.',
    xpReward: 110,
    isPremium: false,
  },

  // Crimson Saint
  {
    id: 'cs-sacred-01',
    archetypeId: 'crimson-saint',
    name: 'The Sacred Witness',
    domain: 'emotional',
    description: 'A ritual for the Crimson Saint to honor their own experience with the same devotion they extend to others.',
    lore: 'The oldest healing traditions understood that the healer must first be healed. The Sacred Witness turns the Crimson Saint\'s extraordinary capacity for presence inward — toward the self that is rarely given the same attention it gives to others.',
    duration: 20,
    steps: [
      'Sit with yourself as you would sit with someone you deeply love who is struggling.',
      'Ask: "What am I carrying right now that no one has asked about?"',
      'Write the answer fully. Give it the time you would give to a friend\'s pain.',
      'Ask: "What do I need that I have not yet allowed myself to receive?"',
      'Write this answer too. Do not immediately think of how to meet it. Simply acknowledge it.',
      'Place your hand over your chest. Breathe. Say: "I see you. You are enough."',
      'Write one thing you will do this week specifically for yourself.',
    ],
    symbolicFocus: 'A candle lit not for another but for yourself — illuminating your own interior.',
    xpReward: 85,
    isPremium: false,
  },
  {
    id: 'cs-devotion-02',
    archetypeId: 'crimson-saint',
    name: 'The Sacred Boundary',
    domain: 'confidence',
    description: 'A ritual for the Crimson Saint to locate and strengthen the boundaries that make their love sustainable.',
    lore: 'Saints in the ancient traditions were not boundaryless — they were boundlessly committed within clearly held sacred lines. This rite builds the structures that allow devotion to sustain rather than deplete.',
    duration: 15,
    steps: [
      'Write the names of three people or situations that currently exhaust your energy.',
      'For each: identify exactly what the depletion is. What is being asked that costs more than it should?',
      'Write what you would need to be able to give what is asked without losing yourself.',
      'Ask: "Is this sustainable? Is this what love actually requires?"',
      'Write one boundary for each relationship. Not to end. To make sustainable.',
      'End with: "My love is not diminished by its limits. It is honored by them."',
    ],
    symbolicFocus: 'A closed door that leads to a garden — boundary as the container that allows growth.',
    xpReward: 100,
    isPremium: false,
  },
];

export function getRitualsForArchetype(archetypeId: string): Ritual[] {
  return RITUALS.filter((r) => r.archetypeId === archetypeId);
}

export function getAllFreeRituals(): Ritual[] {
  return RITUALS.filter((r) => !r.isPremium);
}

export const RITUAL_DOMAIN_LABELS: Record<string, string> = {
  discipline: 'Discipline',
  confidence: 'Confidence',
  emotional: 'Emotional Mastery',
  focus: 'Focus',
  creativity: 'Creativity',
  reflection: 'Deep Reflection',
  ambition: 'Ambition',
  calmness: 'Inner Calm',
};
